handle_user_query:
  description: >
    A user has submitted the following query:

    "{user_query}"

    Your job is to classify and route it to the most appropriate agent in the crew:

    1. Classify the task type:
       - Quick Q&A from KB or DB
       - Full business analysis
       - Visualization/chart generation
       - Strategic business recommendation

    2. Choose the best specialist agent:
       - Data Q&A Expert: for simple metrics and fast DB/KB lookups
       - Enterprise Data Analyst: for deep analysis or fresh data needs
       - Data Visualization Expert: for charts, dashboards, visuals
       - Strategic Business Consultant: for strategy/growth decisions

    3. Construct a task for that agent with clear instructions.

    4. Delegate it using CrewAI delegation. Your delegation MUST be a JSON with all 3 fields:

    Delegation format with these exact fields:
    instruction - what to do
    context - details and background
    coworker - agent name

    5. Evaluate the response quality:
       - Did it fully answer the user?
       - If not, consider rerouting or rephrasing.

    Your final answer MUST include:
    - The result of the delegated task
    - A hidden self-evaluation like:
      <!-- Self-evaluation: Routed to Data Q&A Expert. Reason: Quick sales lookup. -->

  expected_output: >
    A complete response to the user’s query, generated by the delegated agent.
    Include an HTML comment with your routing decision and rationale.