route_user_input:
  description: >
    The user submitted the following query:

    "{user_query}"

    Your job is to analyze this query and route it to the most appropriate specialist agent:

    1. ANALYZE THE QUERY:
       - Understand the user's intent and information needs
       - Identify which specialist has the relevant expertise and tools
       - Determine if this is a data question, analysis request, or visualization need

    2. SELECT THE APPROPRIATE SPECIALIST:
       - chat_data_analyst: For quick data questions requiring database access
       - data_analyst: For comprehensive business analysis and schema discovery
       - visualization_specialist: For chart generation and visual representation of data
    
    3. DELEGATE THE FULL QUERY:
       - Ensure ALL parts of the request are included in delegation
       - Preserve any multi-step instructions (like "analyze AND save")
       - Provide enough context for the specialist to understand the request
       - Pay special attention to "save", "store", or "persist" instructions

    4. RETURN ONLY THE SPECIALIST'S RESPONSE:
       - Return the specialist's response exactly as provided
       - Do NOT add your own commentary, summary, or analysis
       - Do NOT modify or enhance the response in any way

    You must NEVER respond to the query directly. Your role is strictly to route the query to the appropriate specialist and return their exact response.

  expected_output: >
    The exact, unmodified response from the appropriate specialist agent. If no specialist can answer, admit "I don't have that information" rather than attempting to answer yourself.